services:
  db:
    image: postgres:18
    container_name: bounty_db
    restart: unless-stopped
    networks:
      - botnetv2
    env_file:
      - path: ./.env
        required: false 
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mappings/postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bountydb -U bounty"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "5432:5432"

  bot-core:
    build: 
      context: ./
      dockerfile: ./services/bot-core/Dockerfile
    container_name: bot-core
    networks:
      - botnetv2
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - path: ./.env
        required: false 
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mappings/bot-core:/app/data
    restart: unless-stopped

  discord-gateway:
    build: 
      context: ./
      dockerfile: ./services/discord-gateway/Dockerfile
    container_name: discord-gateway
    networks:
      - botnetv2
    ports:
      - 7999:7999
    depends_on:
      bot-core:
        condition: service_healthy
        restart: true
      #blender-service:
      #  condition: service_healthy
      #  restart: true
      db:
        condition: service_healthy
        restart: true
    env_file:
      - path: ./.env
        required: false 
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mappings/discord-gateway:/app/data
    restart: unless-stopped

#  blender-service:
#    build: 
#      context: ./
#      dockerfile: ./services/blender-service/Dockerfile
#    container_name: blender-service
#    depends_on:
#      bot-core:
#        condition: service_healthy
#        restart: true
#    # Comment out/remove below if you don't have a NVidia GPU for use
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
#    networks:
#      - botnetv2
#    ports:
#      - 8001:8001
#    env_file:
#      - path: ./.env
#        required: false 
#    environment:
#      - PUID=${PUID:-1000}
#      - PGID=${PGID:-1000}
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - ./mappings/blender-renderer:/app/data
#    healthcheck:
#      test: curl -s -o /dev/null -f http://localhost:8001/api/v1/health/ || exit 1
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 360s
#    restart: unless-stopped

networks:
  botnetv2:
    name: botnetv2
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: botnetv2_br