"""auto: feat: promote/demote flow correctness + B.90–B.95 (render

Revision ID: 6510020b3335
Revises: 0006
Create Date: 2026-05-15 13:31:09.072782

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6510020b3335"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "players", "player_ships", ["active_ship_id"], ["id"], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "players", type_="foreignkey")
    # ### end Alembic commands ###
