from enum import Enum


class TableNames(Enum):
    Bounty = "bounty"
    Commodity = "commodity"
    CombatLog = "combat_log"
    Criminal = "criminal"
    DuelRequest = "duel_requests"
    DiscordMessage = "discord_message"
    GuildConfigs = "guild_configs"
    GuildShops = "guild_shops"
    Item = "item"
    Module = "module"
    PlayerInventories = "player_inventories"
    PlayerShips = "player_ships"
    Players = "players"
    PrimaryWeapon = "primary_weapon"
    SecondaryWeapon = "secondary_weapon"
    SchemaVersion = "schema"
    Ship = "ship"
    System = "system"
    TurretWeapon = "turret_weapon"
    Users = "users"
    Weapon = "weapon"
    GameEvents = "game_events"
    GameEventPrizes = "game_event_prizes"
    GameEventMetrics = "game_event_metrics"
    EventResults = "event_results"
